language: python
python:
  - "2.7"
  - "3.3"
env:
  - DJANGO_PACKAGE=https://github.com/django/django/archive/stable/1.5.x.zip
  - DJANGO_PACKAGE=https://github.com/django/django/archive/stable/1.6.x.zip
  - DJANGO_PACKAGE=https://github.com/django/django/archive/stable/1.7.x.zip
matrix:
  include:
    - python: "2.6"
      env: DJANGO_PACKAGE=https://github.com/django/django/archive/stable/1.4.x.zip
    - python: "2.7"
      env: DJANGO_PACKAGE=https://github.com/django/django/archive/stable/1.4.x.zip
install:
  - pip install -q $DJANGO_PACKAGE --use-mirrors
  - python setup.py install
  - pip install mock
script: make test
